baseurl = "https://master--mariner-flood-40254.netlify.com/"
title = "Stowarzyszenie im. Richarda Straussa"

[taxonomies]
tag = "tags"
group = "groups"
menu = "menu"

[params]
email = "mateusz.wisniewski@gazeta.pl"
