baseurl = "http://richardstrauss.pubstorm.site"
title = "Stowarzyszenie im. Richarda Straussa"

[taxonomies]
tag = "tags"
group = "groups"
menu = "menu"

[params]
email = "mateusz.wisniewski@gazeta.pl"
